"""CRS parsing, round-tripping, and agreement with the reference implementation.

`tests/data/catrenet_polymer_n6.crs` was generated by CatReNet's own `polymer-tool`
(Huson, Xavier & Steel 2024) and the reference counts below are what CatReNet's
`catrenet-tool` reports on it. Committing both turns an independent implementation
into a permanent regression test that needs no Java to run.
"""
from __future__ import annotations

import pathlib

import pytest

from rafkit.crs import parse_crs, read_crs, to_crs
from rafkit.raf import (catrenet_strictly_autocatalytic, max_raf, max_raf_strict)

DATA = pathlib.Path(__file__).parent / "data" / "catrenet_polymer_n6.crs"

# Reported by catrenet-tool v1.1.0 on the committed fixture.
CATRENET_MAX_RAF = 183
CATRENET_STRICTLY_AUTOCATALYTIC = 175


def _two_way(net, reactions):
    """Collapse the forward/reverse split back to CatReNet's reaction count."""
    return {net.names[r].removesuffix("_rev") for r in reactions}


class TestParsing:
    def test_reversible_becomes_two_directed_reactions(self):
        net = parse_crs("Food: a, b\nr1 : a + b [ab] <-> ab\n")
        assert net.n_reactions == 2
        assert net.names == ("r1", "r1_rev")
        assert net.reactants(0) == net.products(1)
        assert net.catalysts[0] == net.catalysts[1]

    def test_irreversible_stays_one_reaction(self):
        for arrow in ("=>", "->"):
            net = parse_crs(f"Food: a, b\nr1 : a + b [ab] {arrow} ab\n")
            assert net.n_reactions == 1, arrow

    def test_comments_and_blank_lines_are_ignored(self):
        net = parse_crs("# header\n\nFood: a, b\n\nr1 : a + b [ab] => ab  # trailing\n")
        assert net.n_reactions == 1 and len(net.food) == 2

    def test_food_is_indexed_first(self):
        net = parse_crs("Food: a, b\nr1 : a + b [zz] => zz\n")
        assert {net.molecules[i] for i in net.food} == {"a", "b"}

    def test_round_trip_preserves_the_network(self):
        net = read_crs(DATA)
        again = parse_crs(to_crs(net))
        assert again.n_molecules == net.n_molecules
        assert again.n_reactions == net.n_reactions
        assert {net.molecules[m] for m in net.food} == {
            again.molecules[m] for m in again.food}
        assert len(max_raf(again).reactions) == len(max_raf(net).reactions)


class TestAgreesWithCatReNet:
    """The point of the fixture: an independent implementation says the same thing."""

    def test_max_raf_matches_catrenet_exactly(self):
        net = read_crs(DATA)
        assert len(_two_way(net, max_raf(net).reactions)) == CATRENET_MAX_RAF

    def test_strictly_autocatalytic_matches_catrenet_exactly(self):
        net = read_crs(DATA)
        got = catrenet_strictly_autocatalytic(net)
        assert len(_two_way(net, got)) == CATRENET_STRICTLY_AUTOCATALYTIC

    def test_our_strict_raf_is_a_different_stricter_object(self):
        # Documented divergence, not a bug: CatReNet filters the maximal RAF without
        # re-refining, so its result need not be a RAF; ours imposes the condition
        # inside the fixpoint, so it is one -- and is correspondingly smaller.
        net = read_crs(DATA)
        ours = _two_way(net, max_raf_strict(net).reactions)
        theirs = _two_way(net, catrenet_strictly_autocatalytic(net))
        assert len(ours) < len(theirs) < CATRENET_MAX_RAF
        assert ours < theirs, "ours should be a subset of theirs"
